# Generated by Django 4.0.1 on 2022-02-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nazgul', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='text',
            new_name='message',
        ),
    ]
